name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:      
      DOCKER_REGISTRY: docker.io/rma4711      
      DOCKER_IMAGE: rma4711/qnap-git-server      
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      
#      - name: Prepare
#        if: success()
#        id: prepare
#        run: |
#          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
#          echo ::set-output name=docker_image::${DOCKER_IMAGE}
#          echo ::set-output name=version::${GITHUB_RUN_NUMBER}

      - name: Docker Login
        if: success()      
        run: |        
          echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: . 
          platforms: linux/arm/v7
          push: true
          tags: rma4711/qnap-git-server:latest

#      - name: Run Buildx (push image)      
#        if: success()      
#        run: |        
#          docker buildx build \ 
#            --platform ${{ steps.prepare.outputs.docker_platform }} \ 
#            --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \ 
#            --file ./Dockerfile \ 
#            --output type=registry \ 
#            . 
             
# das waren die original steps 
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag DOCKER_IMAGE:$(date +%s)
